### ISSUE TITLE
Instant Kernel Panic on Mojave 10.14.x, Haswell MacBookPro 

### ISSUE THREAD

**Issue by boobang** [sicreative/VoltageShift#19]
Hi, following to the previous topic. I tried to execute these commands..
./voltageshift read 0x???

0x606 0x194 0x1a0 0x610 0xce 0x611 0x639 0x637 0x639 0x198 0x1a20x19c

And after using ./voltageshift 0x637 .The system instantly reboot..
Is there enough information for you? Thank you so much for creating such an amazing kext.
I would provide as many information as I can.

**Comment by sicreative** [comment]
Sorry, currently i am no Haswell machine for tweak, our testing this kext is working on latest devices under latest OS 10.14.6, however Apple locked the BIOS to restrict OC since 2018 models so this kext may not working for overclock but it can adjust the power, it true for windows environment such by XTU, upgrade OS may affect old system for OC because Apple may upgrade the firmware transparently .
