### ISSUE TITLE
El Capitan and Previous CPU compatibility

### ISSUE THREAD

**Issue by asoksevil** [sicreative/VoltageShift#2]
Hi there,

Thanks for this app. I guess it will work better than http://volta.garymathews.com.

Is it Yosemite or El Capitan compatible? Could you make it so it also supports Macs from 2011 (Sandy Bridge,and Ivy Bridge) to 2013? What about Skylake and Kaby Lake?

Thanks!

**Comment by sicreative** [comment]
It may working on Yosemite or above if you complied and test it.
However i only write and test on latest MacOS version so i restricted for 10.12 on binary.

Ivy Bridge should not work because Intel introduced "OC Mailbox" since Haswell.

Skylake use some method of undervoltage should work but I am no device for test it.

I observed XTU how it work and the open source from Intel of Linux driver to find how to offset the voltage, so i am no official documents for fully knowledge how all work, so i restricted this software only for under-voltage.

**Comment by asoksevil** [comment]
Apologies for the late reply.

I see, thank you!
